---

- name: Copy the pre-built local rpm files
  copy:
      src: "../files/slurmrpms/{{item}}"
      dest: /tmp/
  with_items:
    - "slurm-devel-{{ slurm_v }}-1.{{ os_v }}.x86_64.rpm"
  when: install_local == "yes"
  

- name: Install from local rpms SLURM-devel package on master-node
  yum:
    name: "{{ packages }}"
    state: present
    disable_gpg_check: yes
    disable_excludes: all
  vars:
    packages:
    - mailx
    - "/tmp/slurm-devel-{{ slurm_v }}-1.{{ os_v }}.x86_64.rpm"
  when: install_local == "yes"


- name: Install from epel slurm-devel packages on master-node
  yum:
    name: "{{ packages }}"
    state: present
    disable_excludes: all
  vars:
    packages:
      - slurm-devel
  when: install_local == "no"


...
