---
######
## This playbook runs the compute and master slurm setup 
######


- hosts: master:compute
  gather_facts: yes
  become: yes

  roles:
    - slurm_common
  

- hosts: master
  gather_facts: yes
  become: yes


  tasks:
    - include: roles/slurm_master/tasks/slurmdevel.yml

    - name: Add cluster-hostnames in hosts file
      blockinfile:
        path: /etc/hosts
        block: |

          {% for server in groups['all'] %}
             {{ hostvars[server].ansible_host }} {{server }}
          {% endfor %}

  roles:
    - slurm_master

  

- hosts: compute
  gather_facts: yes
  become: yes


  roles:
    - slurm_compute

