---
######
## This playbook runs the compute and master slurm setup 
######


- hosts: master:compute
  gather_facts: yes
  become: yes

  roles:
    - slurm_common
  

- hosts: master
  gather_facts: yes
  become: yes


  roles:
    - slurm_master

  tasks:
    - include: roles/slurm_master/tasks/slurmdevel.yml


- hosts: compute
  gather_facts: yes
  become: yes


  roles:
    - slurm_compute

